# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


woof_pack_chicken3 = Product.create({name: "Woof Pack Life Protection Formula Chicken & Brown Rice Recipe", product_type: "Dry Food", category: "Dog Food", size: "3-lb bag", description: "Woof Pack Life Protection Formula was created for the holistic health and well-being of dogs. All formulas start with real meat, whole grains, garden veggies and fruit, plus added LifeSource Bits, a precise blend of nutrients that have been enhanced with a Super 7 package of antioxidant-rich ingredients. This Chicken & Brown Rice Recipe features delicious, protein-rich deboned chicken and other natural ingredients for a healthy meal your dog will love.", quantity: 100, price: 9.99, brand_id: 1})
woof_pack_chicken6 = Product.create({name: "Woof Pack Life Protection Formula Chicken & Brown Rice Recipe", product_type: "Dry Food", category: "Dog Food", size: "6-lb bag", description: "Woof Pack Life Protection Formula was created for the holistic health and well-being of dogs. All formulas start with real meat, whole grains, garden veggies and fruit, plus added LifeSource Bits, a precise blend of nutrients that have been enhanced with a Super 7 package of antioxidant-rich ingredients. This Chicken & Brown Rice Recipe features delicious, protein-rich deboned chicken and other natural ingredients for a healthy meal your dog will love.", quantity: 100, price: 15.50, brand_id: 1})
woof_pack_chicken15 = Product.create({name: "Woof Pack Life Protection Formula Chicken & Brown Rice Recipe", product_type: "Dry Food", category: "Dog Food", size: "15-lb bag", description: "Woof Pack Life Protection Formula was created for the holistic health and well-being of dogs. All formulas start with real meat, whole grains, garden veggies and fruit, plus added LifeSource Bits, a precise blend of nutrients that have been enhanced with a Super 7 package of antioxidant-rich ingredients. This Chicken & Brown Rice Recipe features delicious, protein-rich deboned chicken and other natural ingredients for a healthy meal your dog will love.", quantity: 100, price: 29.99, brand_id: 1})
woof_pack_chicken24 = Product.create({name: "Woof Pack Life Protection Formula Chicken & Brown Rice Recipe", product_type: "Dry Food", category: "Dog Food", size: "24-lb bag", description: "Woof Pack Life Protection Formula was created for the holistic health and well-being of dogs. All formulas start with real meat, whole grains, garden veggies and fruit, plus added LifeSource Bits, a precise blend of nutrients that have been enhanced with a Super 7 package of antioxidant-rich ingredients. This Chicken & Brown Rice Recipe features delicious, protein-rich deboned chicken and other natural ingredients for a healthy meal your dog will love.", quantity: 100, price: 38.99, brand_id: 1})
woof_pack_chicken30 = Product.create({name: "Woof Pack Life Protection Formula Chicken & Brown Rice Recipe", product_type: "Dry Food", category: "Dog Food", size: "30-lb bag", description: "Woof Pack Life Protection Formula was created for the holistic health and well-being of dogs. All formulas start with real meat, whole grains, garden veggies and fruit, plus added LifeSource Bits, a precise blend of nutrients that have been enhanced with a Super 7 package of antioxidant-rich ingredients. This Chicken & Brown Rice Recipe features delicious, protein-rich deboned chicken and other natural ingredients for a healthy meal your dog will love.", quantity: 100, price: 52.99, brand_id: 1})

woof_pack_salmon3 = Product.create({name: "Woof Pack Life Protection Formula Salmon & Potato Recipe", product_type: "Dry Food", category: "Dog Food", size: "3-lb bag", description: "Woof Pack Life Protection Formula was created for the holistic health and well-being of dogs. All formulas start with real meat, whole grains, garden veggies and fruit, plus added LifeSource Bits, a precise blend of nutrients that have been enhanced with a Super 7 package of antioxidant-rich ingredients. This Salmon & Potato Recipe features delicious, protein-rich salmon and other natural ingredients for a healthy meal your dog will love.", quantity: 100, price: 9.99, brand_id: 1})
woof_pack_salmon6 = Product.create({name: "Woof Pack Life Protection Formula Salmon & Potato Recipe", product_type: "Dry Food", category: "Dog Food", size: "6-lb bag", description: "Woof Pack Life Protection Formula was created for the holistic health and well-being of dogs. All formulas start with real meat, whole grains, garden veggies and fruit, plus added LifeSource Bits, a precise blend of nutrients that have been enhanced with a Super 7 package of antioxidant-rich ingredients. This Salmon & Potato Recipe features delicious, protein-rich salmon and other natural ingredients for a healthy meal your dog will love.", quantity: 100, price: 15.50, brand_id: 1})
woof_pack_salmon15 = Product.create({name: "Woof Pack Life Protection Formula Salmon & Potato Recipe", product_type: "Dry Food", category: "Dog Food", size: "15-lb bag", description: "Woof Pack Life Protection Formula was created for the holistic health and well-being of dogs. All formulas start with real meat, whole grains, garden veggies and fruit, plus added LifeSource Bits, a precise blend of nutrients that have been enhanced with a Super 7 package of antioxidant-rich ingredients. This Salmon & Potato Recipe features delicious, protein-rich salmon and other natural ingredients for a healthy meal your dog will love.", quantity: 100, price: 29.99, brand_id: 1})
woof_pack_salmon24 = Product.create({name: "Woof Pack Life Protection Formula Salmon & Potato Recipe", product_type: "Dry Food", category: "Dog Food", size: "24-lb bag", description: "Woof Pack Life Protection Formula was created for the holistic health and well-being of dogs. All formulas start with real meat, whole grains, garden veggies and fruit, plus added LifeSource Bits, a precise blend of nutrients that have been enhanced with a Super 7 package of antioxidant-rich ingredients. This Salmon & Potato Recipe features delicious, protein-rich salmon and other natural ingredients for a healthy meal your dog will love.", quantity: 100, price: 38.99, brand_id: 1})
woof_pack_salmon30 = Product.create({name: "Woof Pack Life Protection Formula Salmon & Potato Recipe", product_type: "Dry Food", category: "Dog Food", size: "30-lb bag", description: "Woof Pack Life Protection Formula was created for the holistic health and well-being of dogs. All formulas start with real meat, whole grains, garden veggies and fruit, plus added LifeSource Bits, a precise blend of nutrients that have been enhanced with a Super 7 package of antioxidant-rich ingredients. This Salmon & Potato Recipe features delicious, protein-rich salmon and other natural ingredients for a healthy meal your dog will love.", quantity: 100, price: 52.99, brand_id: 1})


toy1 = Product.create({name: "Woof Pack Blue/Orange Ultra Rubber Ball Dog Toy", product_type: "Toy", category: "Dog Toy", size: "2 pack", description: "Trees, rocks, earth...it doesn't matter what these bouncy balls hit, they're gonna fly!", quantity: 100, price: 5})
toy2 = Product.create({name: "Woof Pack Red/White Ultra Rubber Ball Dog Toy", product_type: "Toy", category: "Dog Toy", size: "2 pack", description: "Trees, rocks, earth...it doesn't matter what these bouncy balls hit, they're gonna fly!", quantity: 100, price: 5})
toy3 = Product.create({name: "Woof Pack Marlin the Moose Plush Dog Toy", product_type: "Toy", category: "Dog Toy", size: "Small", description: "Soft and cuddly plush toys made with an extra layer of material, so they’re extra tough.", quantity: 100, price: 7})
toy4 = Product.create({name: "Woof Pack Marlin the Moose Plush Dog Toy", product_type: "Toy", category: "Dog Toy", size: "Medium", description: "Soft and cuddly plush toys made with an extra layer of material, so they’re extra tough.", quantity: 100, price: 10})
toy5 = Product.create({name: "Woof Pack Marlin the Moose Plush Dog Toy", product_type: "Toy", category: "Dog Toy", size: "Large", description: "Soft and cuddly plush toys made with an extra layer of material, so they’re extra tough.", quantity: 100, price: 15})
toy6 = Product.create({name: "Woof Pack Bones & Chews", product_type: "Toy", category: "Dog Toy", size: "One Size", description: "For the ultimate play time, the Rope & Bones Dog Toy offers a chewing challenge and a tug toy all in one.", quantity: 100, price: 8})
toy7 = Product.create({name: "Woof Pack Red Classic Dog Toy", product_type: "Toy", category: "Dog Toy", size: "Small", description: "Give your furry friend a reliable and fun plaything with the Woof Pack Classic Dog Toy.", quantity: 100, price: 13})
toy8 = Product.create({name: "Woof Pack Red Classic Dog Toy", product_type: "Toy", category: "Dog Toy", size: "Medium", description: "Give your furry friend a reliable and fun plaything with the Woof Pack Classic Dog Toy.", quantity: 100, price: 15})
toy9 = Product.create({name: "Woof Pack Red Classic Dog Toy", product_type: "Toy", category: "Dog Toy", size: "Large", description: "Give your furry friend a reliable and fun plaything with the Woof Pack Classic Dog Toy.", quantity: 100, price: 17})
toy10 = Product.create({name: "Woof Pack Blue Classic Dog Toy", product_type: "Toy", category: "Dog Toy", size: "Small", description: "Give your furry friend a reliable and fun plaything with the Woof Pack Classic Dog Toy.", quantity: 100, price: 17})
toy11 = Product.create({name: "Woof Pack Blue Classic Dog Toy", product_type: "Toy", category: "Dog Toy", size: "Medium", description: "Give your furry friend a reliable and fun plaything with the Woof Pack Classic Dog Toy.", quantity: 100, price: 17})
toy12 = Product.create({name: "Woof Pack Blue Classic Dog Toy", product_type: "Toy", category: "Dog Toy", size: "Large", description: "Give your furry friend a reliable and fun plaything with the Woof Pack Classic Dog Toy.", quantity: 100, price: 17})

collar1 = Product.create({name: "Woof Pack Classic Red Collar", product_type: "Collar", category: "Dog Collar", size: "Small", description: "This martingale-style dog collar has an added quick-release snap buckle for easier on and off", quantity: 100, price: 10})
collar2 = Product.create({name: "Woof Pack Classic Red Collar", product_type: "Collar", category: "Dog Collar", size: "Medium", description: "This martingale-style dog collar has an added quick-release snap buckle for easier on and off", quantity: 100, price: 10})
collar3 = Product.create({name: "Woof Pack Classic Red Collar", product_type: "Collar", category: "Dog Collar", size: "Large", description: "This martingale-style dog collar has an added quick-release snap buckle for easier on and off", quantity: 100, price: 10})
collar4 = Product.create({name: "Woof Pack Classic Blue Collar", product_type: "Collar", category: "Dog Collar", size: "Large", description: "This martingale-style dog collar has an added quick-release snap buckle for easier on and off", quantity: 100, price: 10})
collar5 = Product.create({name: "Woof Pack Classic Blue Collar", product_type: "Collar", category: "Dog Collar", size: "Large", description: "This martingale-style dog collar has an added quick-release snap buckle for easier on and off", quantity: 100, price: 10})
collar6 = Product.create({name: "Woof Pack Classic Blue Collar", product_type: "Collar", category: "Dog Collar", size: "Large", description: "This martingale-style dog collar has an added quick-release snap buckle for easier on and off", quantity: 100, price: 10})
collar7 = Product.create({name: "Woof Pack Reflective Collar", product_type: "Collar", category: "Dog Collar", size: "Small", description: "Reflective dog collar that has an added quick-release snap buckle for easier on and off", quantity: 100, price: 25})
collar8 = Product.create({name: "Woof Pack Reflective Collar", product_type: "Collar", category: "Dog Collar", size: "Medium", description: "Reflective dog collar that has an added quick-release snap buckle for easier on and off", quantity: 100, price: 25})
collar9 = Product.create({name: "Woof Pack Reflective Collar", product_type: "Collar", category: "Dog Collar", size: "Large", description: "Reflective dog collar that has an added quick-release snap buckle for easier on and off", quantity: 100, price: 25})


harness1 = Product.create({name: "Woof Pack Comfort Control Dog Harness", product_type: "Harness", category: "Dog Harness", size: "Small", description: "The Woof Pack Comfort Control Dog Harness helps owners get a grip and take control of daily walks.", quantity: 100, price: 10})
harness2 = Product.create({name: "Woof Pack Comfort Control Dog Harness", product_type: "Harness", category: "Dog Harness", size: "Medium", description: "The Woof Pack Comfort Control Dog Harness helps owners get a grip and take control of daily walks.", quantity: 100, price: 10})
harness3 = Product.create({name: "Woof Pack Comfort Control Dog Harness", product_type: "Harness", category: "Dog Harness", size: "Large", description: "The Woof Pack Comfort Control Dog Harness helps owners get a grip and take control of daily walks.", quantity: 100, price: 10})

bed1 = Product.create({name: "Woof Pack Lounger Square Dog Bed", product_type: "Bed", category: "Dog Bed", size: "Small", description: "Extremely cozy and soft, giving your pet the ultimate slumber spot at any time of day.", quantity: 100, price: 35})
bed2 = Product.create({name: "Woof Pack Lounger Square Dog Bed", product_type: "Bed", category: "Dog Bed", size: "Medium", description: "Extremely cozy and soft, giving your pet the ultimate slumber spot at any time of day.", quantity: 100, price: 35})
bed3 = Product.create({name: "Woof Pack Lounger Square Dog Bed", product_type: "Bed", category: "Dog Bed", size: "Large", description: "Extremely cozy and soft, giving your pet the ultimate slumber spot at any time of day.", quantity: 100, price: 35})
